version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-1-20210215
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_CONCURRENT_SESSIONS=5
    ports:
      - "6900:5900"
    shm_size: '2gb'
 
  edge:
    image: selenium/node-edge:4.0.0-beta-1-20210215
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_CONCURRENT_SESSIONS=5
    ports:
      - "6901:5900"
    shm_size: '2gb'
 
  firefox:
    image: selenium/node-firefox:4.0.0-beta-1-20210215
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_CONCURRENT_SESSIONS=5
    ports:
      - "6902:5900"
    shm_size: '2gb'
 
  opera:
    image: selenium/node-opera:4.0.0-beta-1-20210215
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_CONCURRENT_SESSIONS=5
    ports:
      - "6903:5900"
    shm_size: '2gb'
 
  selenium-hub:
    image: selenium/hub:4.0.0-beta-1-20210215
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"